"""Add asset_type, risk, tags, source, last_seen to Asset

Revision ID: 19783a69a103
Revises: 3c9ff5b2bb38
Create Date: 2025-05-17 03:25:18.357822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19783a69a103'
down_revision = '3c9ff5b2bb38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('risk', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('source')
        batch_op.drop_column('tags')
        batch_op.drop_column('risk')
        batch_op.drop_column('asset_type')

    # ### end Alembic commands ###
